"""
Stage C.4 — Research Session Tracking

A Research Session is a named container that groups everything the user does
while investigating a specific topic:

  - queries  : every question asked during the session
  - doc_ids  : every document retrieved across those queries
  - notes    : free-form text notes added by the user or generated by the LLM

Unlike C.1 ConversationMemory (which is per-chat-session), a ResearchSession
is intentionally long-lived and can span many conversation sessions.

Typical lifecycle::

    mgr = ResearchSessionManager(store=mem_store)

    # Start a new research effort
    session = mgr.create("Agentic RAG research", tags=["RAG", "Agents"])
    mgr.set_active(session.session_id)

    # As the user asks questions, queries + docs auto-accumulate via
    # ConversationMemory.add_turn() → manager.on_turn() hook.

    # The user manually adds a note
    mgr.add_note("Consider ReAct pattern for tool calling", source_doc_ids=["doc-42"])

    # Later, inspect everything
    print(mgr.build_session_block())
    # Research Session: Agentic RAG research
    # Tags: RAG, Agents
    # Queries: 7  |  Docs: 12  |  Notes: 1
    # Latest: What is the difference between ReAct and Reflexion?

    # Archive when done
    mgr.archive(session.session_id)

Storage: shared ``MemoryStore`` → ``research_sessions`` + ``research_notes`` tables.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from utils.logger import AppLogger

if TYPE_CHECKING:
    from rag.memory.store import MemoryStore

log = AppLogger.get(__name__)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class ResearchSession:
    """Snapshot of one research session.

    Attributes
    ----------
    session_id : UUID string — stable identifier.
    name       : Human-readable name (e.g., "Agentic RAG research").
    status     : ``"active"`` or ``"archived"``.
    tags       : Topic labels for the session.
    doc_ids    : All unique documents retrieved during this session.
    queries    : All questions asked (in chronological order, may repeat).
    created_at : ISO timestamp.
    updated_at : ISO timestamp (updated on every write).
    """

    session_id: str
    name:       str
    status:     str
    tags:       list[str]   = field(default_factory=list)
    doc_ids:    list[str]   = field(default_factory=list)
    queries:    list[str]   = field(default_factory=list)
    created_at: str         = ""
    updated_at: str         = ""


@dataclass
class ResearchNote:
    """A single note attached to a research session.

    Attributes
    ----------
    note_id        : UUID string — stable identifier.
    session_id     : Parent research session.
    content        : Note text (user-written or LLM-generated).
    source_doc_ids : Documents the note was derived from (may be empty).
    created_at     : ISO timestamp.
    """

    note_id:        str
    session_id:     str
    content:        str
    source_doc_ids: list[str] = field(default_factory=list)
    created_at:     str       = ""


# ---------------------------------------------------------------------------
# ResearchSessionManager
# ---------------------------------------------------------------------------

class ResearchSessionManager:
    """Manages research sessions: creation, tracking, notes, and prompt injection.

    One instance is meant to be shared across the application lifetime (held
    by ``LocalLlamaClient``).  The concept of an *active session* lets the RAG
    engine automatically track queries without the caller specifying a session ID.

    Args
    ----
    store : Shared ``MemoryStore`` instance.
    """

    def __init__(self, store: "MemoryStore") -> None:
        self._store        = store
        self._active_id:   str | None = None   # currently active research session

    # ------------------------------------------------------------------
    # Active session
    # ------------------------------------------------------------------

    def set_active(self, session_id: str) -> None:
        """Set the currently active research session."""
        self._active_id = session_id
        log.info("ResearchSessionManager: active session → %s", session_id)

    def clear_active(self) -> None:
        """Clear the active session (subsequent on_turn calls are no-ops)."""
        self._active_id = None

    @property
    def active_session_id(self) -> str | None:
        """Return the active session ID, or None if none is set."""
        return self._active_id

    def get_active_session(self) -> ResearchSession | None:
        """Return the active ResearchSession dataclass, or None."""
        if self._active_id is None:
            return None
        return self.get(self._active_id)

    # ------------------------------------------------------------------
    # Session CRUD
    # ------------------------------------------------------------------

    def create(
        self,
        name: str,
        tags: list[str] = [],
    ) -> ResearchSession:
        """Create and persist a new research session.

        Returns the created ``ResearchSession`` (with a fresh UUID).
        Does NOT automatically set this as the active session.
        """
        sid = str(uuid.uuid4())
        self._store.create_research_session(sid, name, tags=list(tags))
        log.info("ResearchSessionManager: created session %r (%s)", name, sid)
        return self.get(sid)  # type: ignore[return-value]

    def get(self, session_id: str) -> ResearchSession | None:
        """Return a ``ResearchSession`` by ID, or None if not found."""
        row = self._store.get_research_session(session_id)
        return self._row_to_session(row) if row else None

    def get_by_name(self, name: str) -> ResearchSession | None:
        """Return the most recently created session with this *name*, or None."""
        row = self._store.get_research_session_by_name(name)
        return self._row_to_session(row) if row else None

    def list_active(self) -> list[ResearchSession]:
        """Return all active research sessions, newest first."""
        return [self._row_to_session(r) for r in self._store.list_research_sessions("active")]

    def list_archived(self) -> list[ResearchSession]:
        """Return all archived research sessions, newest first."""
        return [self._row_to_session(r) for r in self._store.list_research_sessions("archived")]

    def archive(self, session_id: str) -> None:
        """Mark a session as archived.  Clears the active session if it matches."""
        self._store.update_research_session_status(session_id, "archived")
        if self._active_id == session_id:
            self._active_id = None
        log.info("ResearchSessionManager: archived %s", session_id)

    def restore(self, session_id: str) -> None:
        """Restore an archived session to active status."""
        self._store.update_research_session_status(session_id, "active")

    def delete(self, session_id: str) -> None:
        """Permanently delete a session and all its notes."""
        self._store.delete_research_session(session_id)
        if self._active_id == session_id:
            self._active_id = None
        log.info("ResearchSessionManager: deleted %s", session_id)

    # ------------------------------------------------------------------
    # Query tracking (called automatically via on_turn hook)
    # ------------------------------------------------------------------

    def on_turn(self, query: str, doc_ids: list[str] = []) -> None:
        """Record a Q-A turn into the *active* session (no-op if none is set).

        Called by ``ConversationMemory.add_turn()`` when a research session
        is wired in.
        """
        if self._active_id is None:
            return
        self._store.add_query_to_research_session(
            self._active_id, query, doc_ids=list(doc_ids)
        )

    # ------------------------------------------------------------------
    # Notes
    # ------------------------------------------------------------------

    def add_note(
        self,
        content:        str,
        session_id:     str | None  = None,
        source_doc_ids: list[str]   = [],
    ) -> ResearchNote:
        """Add a note to *session_id* (or the active session if None).

        Args
        ----
        content        : Note text.
        session_id     : Target session; defaults to the active session.
        source_doc_ids : Documents this note was derived from.

        Raises
        ------
        ValueError : If neither *session_id* nor an active session is set.
        """
        sid = session_id or self._active_id
        if sid is None:
            raise ValueError(
                "add_note: no session_id supplied and no active session is set"
            )
        note_id = str(uuid.uuid4())
        self._store.add_research_note(
            note_id=note_id,
            session_id=sid,
            content=content,
            source_doc_ids=list(source_doc_ids),
        )
        return ResearchNote(
            note_id=note_id,
            session_id=sid,
            content=content,
            source_doc_ids=list(source_doc_ids),
        )

    def get_notes(self, session_id: str | None = None) -> list[ResearchNote]:
        """Return all notes for *session_id* (or the active session), oldest first."""
        sid = session_id or self._active_id
        if sid is None:
            return []
        rows = self._store.get_research_notes(sid)
        return [
            ResearchNote(
                note_id=r["note_id"],
                session_id=r["session_id"],
                content=r["content"],
                source_doc_ids=r["source_doc_ids"],
                created_at=r["created_at"],
            )
            for r in rows
        ]

    def delete_note(self, note_id: str) -> None:
        """Delete a single note by *note_id*."""
        self._store.delete_research_note(note_id)

    # ------------------------------------------------------------------
    # Prompt integration
    # ------------------------------------------------------------------

    def build_session_block(self, session_id: str | None = None) -> str:
        """Return a compact block for injection into the RAG prompt.

        Describes the active research session (doc count, query count, notes,
        and the most-recent question).  Returns an empty string when there
        is no session or the session is empty.

        Example output::

            Research Session: Agentic RAG research
            Tags: RAG, Agents
            Queries: 7  |  Docs: 12  |  Notes: 1
            Latest: What is the difference between ReAct and Reflexion?
        """
        sid = session_id or self._active_id
        if sid is None:
            return ""
        session = self.get(sid)
        if session is None:
            return ""
        if not session.queries and not session.doc_ids:
            return ""

        lines = [f"Research Session: {session.name}"]
        if session.tags:
            lines.append(f"Tags: {', '.join(session.tags)}")

        notes     = self.get_notes(sid)
        query_cnt = len(session.queries)
        doc_cnt   = len(session.doc_ids)
        note_cnt  = len(notes)
        lines.append(f"Queries: {query_cnt}  |  Docs: {doc_cnt}  |  Notes: {note_cnt}")

        if session.queries:
            lines.append(f"Latest: {session.queries[-1]}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _row_to_session(row: dict) -> ResearchSession:
        return ResearchSession(
            session_id=row["session_id"],
            name=row["name"],
            status=row["status"],
            tags=row["tags"],
            doc_ids=row["doc_ids"],
            queries=row["queries"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )
