"""
B.3 Topic Clustering — embedding-based topic discovery.

Pipeline
--------
1. Fetch all chunk embeddings (and texts) from Chroma.
2. Run KMeans to assign each chunk to a cluster.
3. For each cluster: pick the K most representative docs (closest to centroid)
   and ask the LLM for a short snake_case topic label  (e.g. "topic_rag").
4. Return a TopicMap: cluster_int → topic_id string, plus per-chunk assignments.
   Call assign() to write topic_id into Chroma metadata.

Usage
-----
    clusterer = TopicClusterer(llm=client.llm, db=client.db)
    topic_map = clusterer.fit_and_assign(n_clusters=8)
    # → each Chroma chunk now has metadata["topic_id"] = "topic_rag" etc.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np
from sklearn.cluster import KMeans

from rag.prompt import TOPIC_LABEL_PROMPT
from utils.logger import AppLogger

if TYPE_CHECKING:
    from langchain_chroma import Chroma
    from langchain_core.language_models import BaseLanguageModel

log = AppLogger.get(__name__)

_SLUG_RE = re.compile(r"[^a-z0-9_]")


def _to_slug(text: str) -> str:
    """Normalise raw LLM output into a safe snake_case topic_id.

    Examples
    --------
        "Reinforcement Learning"  → "topic_reinforcement_learning"
        "topic_rag"               → "topic_rag"
        "  RAG & Retrieval! "     → "topic_rag___retrieval_"  (then cleaned)
    """
    text = text.strip().lower()
    # Strip common prefixes the LLM might include
    for prefix in ("topic_", "topic:", "label:", "category:"):
        if text.startswith(prefix):
            text = text[len(prefix):].strip()
            break
    text = _SLUG_RE.sub("_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return "topic_" + text[:40]


@dataclass
class TopicMap:
    """Output of TopicClusterer.fit().

    Attributes
    ----------
    cluster_labels : int → "topic_xxx" for each KMeans cluster.
    chunk_topics   : chroma_id → "topic_xxx" for every processed chunk.
    n_clusters     : actual number of clusters used (may be reduced when
                     the corpus is smaller than the requested n_clusters).
    n_chunks       : total number of chunks processed.
    """

    cluster_labels: dict[int, str]
    chunk_topics:   dict[str, str]
    n_clusters:     int = 0
    n_chunks:       int = 0


class TopicClusterer:
    """Embedding-based topic clustering for knowledge chunks.

    Clusters chunks in a Chroma collection using KMeans and labels each
    cluster with a human-readable topic_id generated by the LLM.

    Args
    ----
    llm          : LLM used to label cluster centroids.
    db           : Main Chroma collection (source of embeddings + texts).
    n_repr       : Number of representative docs (closest to centroid) to
                   feed the LLM when naming a cluster.
    random_state : KMeans random seed for reproducibility.
    """

    def __init__(
        self,
        llm:          "BaseLanguageModel",
        db:           "Chroma",
        n_repr:       int = 5,
        random_state: int = 42,
    ) -> None:
        self._llm          = llm
        self._db           = db
        self._n_repr       = n_repr
        self._random_state = random_state

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def fit(self, n_clusters: int = 8, doc_id: str | None = None) -> TopicMap:
        """Cluster chunks and label topics with the LLM.

        Args
        ----
        n_clusters : Desired number of KMeans clusters (topics).  Reduced
                     automatically when fewer chunks are available.
        doc_id     : If given, cluster only chunks belonging to this document.

        Returns
        -------
        TopicMap with cluster_labels and per-chunk chunk_topics.
        """
        where = {"doc_id": {"$eq": doc_id}} if doc_id else None
        result = self._db.get(
            where=where,
            include=["embeddings", "documents"],
        )
        ids        = result.get("ids")        or []
        raw_emb    = result.get("embeddings")
        embeddings = raw_emb if raw_emb is not None else []
        documents  = result.get("documents")  or []

        if not ids:
            log.warning("fit: no chunks found (doc_id=%r)", doc_id)
            return TopicMap(cluster_labels={}, chunk_topics={}, n_clusters=0, n_chunks=0)

        if len(ids) < n_clusters:
            log.warning(
                "fit: corpus has %d chunks < n_clusters=%d — reducing n_clusters",
                len(ids), n_clusters,
            )
            n_clusters = max(1, len(ids))

        X = np.array(embeddings, dtype=np.float32)
        km = KMeans(n_clusters=n_clusters, random_state=self._random_state, n_init="auto")
        km.fit(X)

        labels    = km.labels_            # (n_chunks,) int array
        centroids = km.cluster_centers_   # (n_clusters, dim) float array

        # For each cluster: pick n_repr docs closest to the centroid
        cluster_repr: dict[int, list[str]] = {}
        for cluster_int in range(n_clusters):
            mask    = labels == cluster_int
            indices = np.where(mask)[0]
            if len(indices) == 0:
                cluster_repr[cluster_int] = []
                continue
            dists   = np.linalg.norm(X[indices] - centroids[cluster_int], axis=1)
            sorted_ = indices[np.argsort(dists)]
            cluster_repr[cluster_int] = [
                documents[i] or "" for i in sorted_[: self._n_repr]
            ]

        # Label each cluster with the LLM
        cluster_labels: dict[int, str] = {}
        for cluster_int in range(n_clusters):
            repr_docs = cluster_repr[cluster_int]
            cluster_labels[cluster_int] = self._label_cluster(cluster_int, repr_docs)

        chunk_topics = {
            chroma_id: cluster_labels[int(labels[i])]
            for i, chroma_id in enumerate(ids)
        }

        log.info(
            "fit: %d chunks → %d clusters  (doc_id=%r)",
            len(ids), n_clusters, doc_id,
        )
        for c_int, t_id in cluster_labels.items():
            count = int(np.sum(labels == c_int))
            log.debug("  cluster %d: %s  (%d chunks)", c_int, t_id, count)

        return TopicMap(
            cluster_labels=cluster_labels,
            chunk_topics=chunk_topics,
            n_clusters=n_clusters,
            n_chunks=len(ids),
        )

    def assign(self, topic_map: TopicMap) -> int:
        """Write topic_id into Chroma metadata for every chunk in *topic_map*.

        Merges with existing metadata (does not overwrite other fields).

        Returns
        -------
        Number of chunks updated.
        """
        if not topic_map.chunk_topics:
            return 0

        ids = list(topic_map.chunk_topics.keys())

        # Fetch current metadata so we can merge rather than overwrite
        result    = self._db.get(ids=ids, include=["metadatas"])
        metadatas = result.get("metadatas") or [{}] * len(ids)

        new_metas = [
            {**(m or {}), "topic_id": topic_map.chunk_topics[chroma_id]}
            for chroma_id, m in zip(ids, metadatas)
        ]
        self._db._collection.update(ids=ids, metadatas=new_metas)
        log.info("assign: wrote topic_id for %d chunks", len(ids))
        return len(ids)

    def fit_and_assign(
        self, n_clusters: int = 8, doc_id: str | None = None
    ) -> TopicMap:
        """Convenience: run fit() then assign()."""
        topic_map = self.fit(n_clusters=n_clusters, doc_id=doc_id)
        self.assign(topic_map)
        return topic_map

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _label_cluster(self, cluster_int: int, repr_docs: list[str]) -> str:
        """Ask the LLM to generate a snake_case topic label for a cluster."""
        if not repr_docs:
            return f"topic_cluster_{cluster_int}"

        combined = "\n---\n".join(d for d in repr_docs if d)
        if not combined.strip():
            return f"topic_cluster_{cluster_int}"

        prompt = TOPIC_LABEL_PROMPT.format(text=combined)
        try:
            response = self._llm.invoke(prompt)
            raw      = response.content if hasattr(response, "content") else str(response)
            slug     = _to_slug(raw.strip())
            log.debug("  cluster %d label: %r", cluster_int, slug)
            return slug
        except Exception as exc:  # noqa: BLE001
            log.warning("  cluster %d: LLM error — %s  (using fallback)", cluster_int, exc)
            return f"topic_cluster_{cluster_int}"
