"""
Phase 0 — Core domain model for the knowledge system.

Hierarchy
---------
    Workspace
        └── Page           (Notion page or local document)
                └── Block  (atomic content unit: paragraph, heading, code, …)
                        └── Chunk  (embedding unit, derived from 1-N Blocks)

DocumentVersion records every point-in-time snapshot of a Page and enables:
    - Incremental indexing  (skip pages whose content has not changed)
    - Time travel           (retrieve the knowledge state at any version)
    - Knowledge evolution   (compare diff_summary across versions)

Design notes
------------
- All enums use str as their mixin so they serialise naturally to JSON/YAML.
- BlockType values for Notion-origin content match the Notion API verbatim.
  LOCAL_* values are used for content from local files (PDF, Markdown, text).
- Chunk.to_chroma_meta() / to_document() bridge this model to the existing
  LangChain + Chroma retrieval layer while remaining backward-compatible with
  the legacy schema.py metadata keys.
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class BlockType(str, Enum):
    """All block types that can appear in a Page.

    Notion API type strings are used verbatim where applicable.
    LOCAL_* variants cover content that originates from local file parsers.
    """

    # ── Text blocks (Notion API) ──────────────────────────────────────────
    PARAGRAPH          = "paragraph"
    HEADING_1          = "heading_1"
    HEADING_2          = "heading_2"
    HEADING_3          = "heading_3"
    HEADING_4          = "heading_4"
    BULLETED_LIST_ITEM = "bulleted_list_item"
    NUMBERED_LIST_ITEM = "numbered_list_item"
    TO_DO              = "to_do"
    TOGGLE             = "toggle"
    CODE               = "code"
    QUOTE              = "quote"
    CALLOUT            = "callout"
    EQUATION           = "equation"

    # ── Structural blocks (Notion API) ────────────────────────────────────
    TABLE              = "table"
    TABLE_ROW          = "table_row"
    DIVIDER            = "divider"
    TABLE_OF_CONTENTS  = "table_of_contents"

    # ── Reference / navigation blocks (Notion API) ───────────────────────
    CHILD_PAGE         = "child_page"
    CHILD_DATABASE     = "child_database"

    # ── Media / embed blocks (Notion API) ────────────────────────────────
    IMAGE              = "image"
    VIDEO              = "video"
    AUDIO              = "audio"
    FILE               = "file"
    PDF                = "pdf"
    BOOKMARK           = "bookmark"
    EMBED              = "embed"

    # ── Local-file-origin types ───────────────────────────────────────────
    # Used when content comes from the local file parsers (not Notion API).
    LOCAL_HEADING      = "local_heading"    # Markdown heading
    LOCAL_PARAGRAPH    = "local_paragraph"  # plain-text paragraph
    LOCAL_CODE         = "local_code"       # fenced code block (Markdown)
    LOCAL_TABLE        = "local_table"      # Markdown GFM table
    LOCAL_PAGE_TEXT    = "local_page_text"  # raw page content from PDF

    UNSUPPORTED        = "unsupported"


class ChangeType(str, Enum):
    """The nature of the change captured in a DocumentVersion."""

    CREATED = "created"
    UPDATED = "updated"
    DELETED = "deleted"


# ---------------------------------------------------------------------------
# Core entities
# ---------------------------------------------------------------------------

@dataclass
class Workspace:
    """Top-level namespace that groups related Pages.

    Can represent a Notion workspace, a local project folder, or any other
    logical container for a coherent body of documents.

    Attributes:
        id                   : UUID string (auto-generated by Workspace.new()).
        name                 : Human-readable label used in Chroma metadata.
        description          : Optional long-form description.
        notion_workspace_id  : Notion workspace UUID, when syncing from Notion.
        created_at           : UTC creation timestamp.
        metadata             : Extensible key-value store for future fields.
    """

    id:                   str
    name:                 str
    description:          str       = ""
    notion_workspace_id:  str | None = None
    created_at:           datetime  = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata:             dict      = field(default_factory=dict)

    @staticmethod
    def new(name: str, **kwargs) -> "Workspace":
        """Factory: create a new Workspace with an auto-generated UUID."""
        return Workspace(id=str(uuid.uuid4()), name=name, **kwargs)


@dataclass
class Page:
    """A single document — a Notion page, a PDF, a Markdown file, or plain text.

    One Page corresponds to one logical document.  All Chunks produced from
    this Page share the same ``id`` as their ``page_id``.

    The field names intentionally match the keys in ``rag/ingest/schema.py``
    so that Chunks produced from this model are compatible with the existing
    LangChain + Chroma retrieval pipeline.

    Attributes:
        id             : UUID string (auto-generated by Page.new()).
        workspace_id   : Parent Workspace UUID.
        title          : Human-readable document title.
        source         : Absolute file path (local) or Notion page URL.
        document_type  : "pdf" | "markdown" | "text" | "notion".
        tags           : Tag list; stored as a comma-joined string in Chroma.
        importance     : Caller-assigned priority weight (0.0 = neutral).
        notion_page_id : Notion page UUID (only set for Notion-origin pages).
        parent_page_id : UUID of the parent Page for nested documents.
        created_time   : UTC timestamp of first creation.
        updated_time   : UTC timestamp of last content change.
        metadata       : Extensible key-value store.
    """

    id:             str
    workspace_id:   str
    title:          str
    source:         str
    document_type:  str       = "text"
    tags:           list[str] = field(default_factory=list)
    importance:     float     = 0.0
    notion_page_id: str | None = None
    parent_page_id: str | None = None
    created_time:   datetime  = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_time:   datetime  = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata:       dict      = field(default_factory=dict)

    @staticmethod
    def new(workspace_id: str, title: str, source: str, **kwargs) -> "Page":
        """Factory: create a new Page with an auto-generated UUID."""
        return Page(
            id=str(uuid.uuid4()),
            workspace_id=workspace_id,
            title=title,
            source=source,
            **kwargs,
        )

    @property
    def doc_id(self) -> str:
        """Alias used by the existing retrieval layer (= self.id)."""
        return self.id


@dataclass
class Block:
    """Atomic content unit within a Page.

    Mirrors the Notion block model.  For local-file content the ``block_type``
    uses the LOCAL_* values from BlockType.

    ``order`` is the 0-based position in a depth-first traversal of the page
    block tree, making it stable and sort-friendly.

    ``parent_block_id`` captures nesting: a toggle's children point back to
    the toggle block, list items point to their list container, etc.

    Attributes:
        id               : UUID string.
        page_id          : Parent Page UUID.
        block_type       : See BlockType enum.
        content          : Plain-text content of this block (stripped of markup).
        order            : 0-based depth-first position within the Page.
        parent_block_id  : UUID of the enclosing block, or None for top-level.
        notion_block_id  : Notion block UUID (only set for Notion-origin blocks).
        metadata         : Type-specific extras, e.g.:
                             code block  → {"language": "python"}
                             heading     → {"level": 2, "is_toggleable": False}
                             to_do       → {"checked": False}
                             table_row   → {"cells": [["col1"], ["col2"]]}
    """

    id:              str
    page_id:         str
    block_type:      BlockType
    content:         str
    order:           int
    parent_block_id: str | None = None
    notion_block_id: str | None = None
    metadata:        dict       = field(default_factory=dict)

    @staticmethod
    def new(
        page_id: str,
        block_type: BlockType,
        content: str,
        order: int,
        **kwargs,
    ) -> "Block":
        """Factory: create a new Block with an auto-generated UUID."""
        return Block(
            id=str(uuid.uuid4()),
            page_id=page_id,
            block_type=block_type,
            content=content,
            order=order,
            **kwargs,
        )

    @property
    def is_heading(self) -> bool:
        """True if this block is any heading type."""
        return self.block_type in {
            BlockType.HEADING_1,
            BlockType.HEADING_2,
            BlockType.HEADING_3,
            BlockType.HEADING_4,
            BlockType.LOCAL_HEADING,
        }

    @property
    def is_text_bearing(self) -> bool:
        """True if this block type carries indexable plain text."""
        _TEXT_TYPES = {
            BlockType.PARAGRAPH,
            BlockType.HEADING_1, BlockType.HEADING_2,
            BlockType.HEADING_3, BlockType.HEADING_4,
            BlockType.BULLETED_LIST_ITEM, BlockType.NUMBERED_LIST_ITEM,
            BlockType.TO_DO, BlockType.TOGGLE, BlockType.CODE,
            BlockType.QUOTE, BlockType.CALLOUT, BlockType.EQUATION,
            BlockType.TABLE_ROW,
            BlockType.LOCAL_HEADING, BlockType.LOCAL_PARAGRAPH,
            BlockType.LOCAL_CODE, BlockType.LOCAL_TABLE,
            BlockType.LOCAL_PAGE_TEXT,
        }
        return self.block_type in _TEXT_TYPES


@dataclass
class Chunk:
    """Embedding unit derived from one or more consecutive Blocks within a Page.

    The embedding vector itself lives in the vector store (Chroma).
    This model carries the structural metadata needed for:

        - Retrieval-time filtering (workspace, tags, importance, date range)
        - Chunk reconstruction given ``block_ids``
        - Change detection via ``content_hash``
        - BM25 hybrid search (uses plain-text ``content``)

    Attributes:
        id          : UUID string.
        page_id     : Parent Page UUID.
        content     : Plain-text content sent to the embedding model.
        chunk_index : 0-based sequential index within the Page.
        section     : Nearest preceding heading text (empty string if none).
        block_ids   : Ordered list of Block UUIDs that make up this Chunk.
        token_count : Approximate token count (0 if not yet computed).
        metadata    : Extensible key-value store.
    """

    id:          str
    page_id:     str
    content:     str
    chunk_index: int
    section:     str       = ""
    block_ids:   list[str] = field(default_factory=list)
    token_count: int       = 0
    metadata:    dict      = field(default_factory=dict)

    @staticmethod
    def new(page_id: str, content: str, chunk_index: int, **kwargs) -> "Chunk":
        """Factory: create a new Chunk with an auto-generated UUID."""
        return Chunk(
            id=str(uuid.uuid4()),
            page_id=page_id,
            content=content,
            chunk_index=chunk_index,
            **kwargs,
        )

    @property
    def content_hash(self) -> str:
        """SHA-256 of the chunk content — used for change detection."""
        return hashlib.sha256(self.content.encode()).hexdigest()

    def to_chroma_meta(
        self,
        page: "Page",
        workspace: "Workspace",
        *,
        embedding_version: str = "",
        chunk_version: str = "",
        content_type: str = "",
    ) -> dict:
        """Build a canonical Chroma-safe metadata dict via ChunkMetadata.

        Delegates to ChunkMetadata.from_page() so both the Notion and local-file
        pipelines emit the same v1 canonical schema.
        """
        from rag.knowledge.metadata import ChunkMetadata
        return ChunkMetadata.from_page(
            page,
            workspace,
            chunk_id=self.chunk_index,
            section=self.section,
            heading_path=[self.section] if self.section else [],
            block_id=self.block_ids[0] if self.block_ids else "",
            block_type=str(self.metadata.get("block_type", "")),
            content_type=content_type or str(self.metadata.get("content_type", "")),
            embedding_version=embedding_version,
            chunk_version=chunk_version,
        ).to_chroma()

    def to_document(
        self,
        page: "Page",
        workspace: "Workspace",
        *,
        embedding_version: str = "",
        chunk_version: str = "",
        content_type: str = "",
    ):
        """Return a LangChain Document ready for vector-store indexing."""
        from langchain_core.documents import Document as LCDocument
        return LCDocument(
            page_content=self.content,
            metadata=self.to_chroma_meta(
                page, workspace,
                embedding_version=embedding_version,
                chunk_version=chunk_version,
                content_type=content_type,
            ),
        )


@dataclass
class DocumentVersion:
    """Point-in-time snapshot of a Page's content.

    A new DocumentVersion is created whenever a Page is indexed for the
    first time (ChangeType.CREATED) or re-indexed after its content changes
    (ChangeType.UPDATED).  Deleted pages are recorded with ChangeType.DELETED.

    Incremental indexing workflow
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1. Fetch all Blocks for a Page.
    2. Compute ``DocumentVersion.compute_hash(blocks)``.
    3. Compare against the latest stored ``content_hash`` for that page.
    4. If unchanged → skip.  If changed → re-chunk, re-embed, save new version.

    Attributes:
        id           : UUID string.
        page_id      : Parent Page UUID.
        version      : Monotonically increasing integer per Page (starts at 1).
        content_hash : SHA-256 of sorted, concatenated block plain-text content.
        created_at   : UTC timestamp when this version was recorded.
        change_type  : CREATED | UPDATED | DELETED.
        chunk_count  : Number of Chunks produced at this version.
        diff_summary : Human-readable change description (LLM-generated later).
    """

    id:           str
    page_id:      str
    version:      int
    content_hash: str
    created_at:   datetime
    change_type:  ChangeType
    chunk_count:  int = 0
    diff_summary: str = ""

    @staticmethod
    def new(
        page_id: str,
        version: int,
        content_hash: str,
        change_type: ChangeType,
        **kwargs,
    ) -> "DocumentVersion":
        """Factory: create a new DocumentVersion with an auto-generated UUID."""
        return DocumentVersion(
            id=str(uuid.uuid4()),
            page_id=page_id,
            version=version,
            content_hash=content_hash,
            created_at=datetime.now(timezone.utc),
            change_type=change_type,
            **kwargs,
        )

    @staticmethod
    def compute_hash(blocks: list[Block]) -> str:
        """Compute a stable content hash from a list of Blocks.

        Blocks are sorted by ``order`` before hashing so the hash is
        independent of retrieval order.
        """
        combined = "".join(
            b.content for b in sorted(blocks, key=lambda b: b.order)
        )
        return hashlib.sha256(combined.encode()).hexdigest()
